const predefinedAnswers = [
  { question: "hi", answer: "Hello! How can I assist you today?" },
  { question: "hello", answer: "Hi there! How can I help?" },
  { question: "hey", answer: "Hey! What can I do for you?" },
  { question: "hii", answer: "Hello! How's it going?" },
  { question: "how are you", answer: "I'm just a bot, but I'm here to help! How about you?" },
  { question: "what's up", answer: "Not much! How can I assist you today?" },
  { question: "good morning", answer: "Good morning! How can I help you?" },
  { question: "good afternoon", answer: "Good afternoon! What can I do for you?" },
  { question: "good evening", answer: "Good evening! How can I assist you today?" },
  { question: "hi bot", answer: "Hello! I'm here to help you." },
  { question: "how's it going", answer: "Everything’s great here! How can I help you?" },
  { question: "hey there", answer: "Hey! How can I assist you?" },
  { question: "are you there", answer: "Yes, I'm here! How can I assist you?" },
  { question: "how's your day", answer: "I'm just a bot, but I'm having a productive day helping people!" },
  { question: "good night", answer: "Good night! Feel free to ask me anything before you log off." },
  { question: "what can you do", answer: "I can assist with questions about products, orders, delivery, and more!" },
  { question: "who are you", answer: "I'm a chatbot here to assist you with any inquiries." },
  { question: "what's your name", answer: "I'm your virtual assistant! How can I help today?" },
  { question: "help", answer: "I'm here to help! What do you need assistance with?" },
  { question: "can you help me", answer: "Of course! What do you need help with?" },
  { question: "thanks", answer: "You're welcome! Let me know if you need anything else." },
  { question: "thank you", answer: "You're welcome! I'm happy to assist." },
  { question: "goodbye", answer: "Goodbye! Have a great day!" },
  { question: "bye", answer: "Bye! Feel free to reach out if you need further assistance." },
  { question: "talk to you later", answer: "Talk to you soon! Let me know if you have any questions." },
  { question: "see you later", answer: "See you! Feel free to reach out anytime." },
  { question: "ok", answer: "Got it! Anything else I can help with?" },
  { question: "yes", answer: "Great! How can I assist further?" },
  { question: "no", answer: "Alright, let me know if you change your mind!" },
  { question: "sure", answer: "Sure! What would you like assistance with?" },
  { question: "cool", answer: "Glad you think so! Anything else I can do for you?" },
  { question: "awesome", answer: "I'm happy to hear that! How can I assist you further?" },
  { question: "what's new", answer: "We have some great new products! What are you interested in?" },
  { question: "tell me more", answer: "Sure! What would you like to know more about?" },
  { question: "hello", answer: "Hello! How can I assist you today?" },
  { question: "help", answer: "I'm here to assist you with your questions." },
  { question: "price", answer: "The price varies depending on the product. Could you specify which product?" },
  { question: "delivery", answer: "Delivery takes between 3-5 business days." },
  { question: "payment", answer: "We accept credit cards, PayPal, and other digital payment methods." },
  { question: "refund", answer: "Refunds are processed within 7 working days after receiving the returned item." },
  { question: "support", answer: "You can reach our support team 24/7 via email or live chat." },
  { question: "bye", answer: "Goodbye! Feel free to reach out if you need further assistance." },
  { question: "thanks", answer: "You're welcome! Let me know if you need anything else." },
  { question: "open hours", answer: "We are open Monday to Friday from 9 AM to 6 PM." },
  { question: "products", answer: "We offer a wide range of products including electronics, apparel, and home goods." },
  { question: "what", answer: "Could you please specify what you're looking for?" },
  { question: "where", answer: "Where would you like assistance with?" },
  { question: "who", answer: "Who would you like to know about?" },
  { question: "when", answer: "When do you need assistance?" },
  { question: "why", answer: "Could you clarify why you need help?" },
  { question: "how", answer: "How can I assist you today?" },
  { question: "can", answer: "Can you provide more details on what you need?" },
  { question: "could", answer: "Could you please elaborate on your request?" },
  { question: "will", answer: "Will you need help with something specific?" },
  { question: "would", answer: "Would you like more information on our services?" },
  { question: "need", answer: "What do you need help with today?" },
  { question: "help me", answer: "I'm here to help! What do you need assistance with?" },
  { question: "assist", answer: "How can I assist you further?" },
  { question: "info", answer: "What information are you looking for?" },
  { question: "tell me", answer: "Tell me what you'd like to know!" },
  { question: "question", answer: "What question do you have?" },
  { question: "please", answer: "Please let me know how I can assist you." },
  { question: "example", answer: "Could you provide an example of what you're looking for?" },
  { question: "details", answer: "What details do you need assistance with?" },
  { question: "like", answer: "What do you like to know about our services?" },
  { question: "love", answer: "What do you love about our products?" },
  { question: "hate", answer: "What do you dislike about our services?" },
  { question: "want", answer: "What do you want help with?" },
  { question: "helpful", answer: "How can I be more helpful to you?" },
  { question: "search", answer: "What would you like to search for?" },
  { question: "give me", answer: "Give me a moment to find that information for you." },
  { question: "find", answer: "What are you looking to find?" },
  { question: "show", answer: "What would you like me to show you?" },
  { question: "learn", answer: "What would you like to learn about?" },
  { question: "recommend", answer: "What would you like me to recommend?" },
  { question: "buy", answer: "What would you like to buy?" },
  { question: "order", answer: "What would you like to order?" },
  { question: "checkout", answer: "Are you ready to checkout?" },
  { question: "info", answer: "What information do you need?" },
  { question: "please", answer: "Please let me know how I can assist you." },
  { question: "details", answer: "What details are you looking for?" },
  { question: "status", answer: "What would you like the status of?" },
  { question: "help", answer: "How can I help you today?" },
  { question: "problem", answer: "What problem are you experiencing?" },
  { question: "issue", answer: "Could you describe the issue?" },
  { question: "question", answer: "What question do you have?" },
  { question: "need help", answer: "I'm here to help! What do you need assistance with?" },
  { question: "suggest", answer: "What would you like me to suggest?" },
  { question: "chat", answer: "Let's chat! What would you like to talk about?" },
  { question: "search", answer: "What are you looking for?" },
  { question: "talk", answer: "What would you like to talk about?" },
  { question: "query", answer: "What query do you have?" },
  { question: "find out", answer: "What would you like to find out?" },
  { question: "clarify", answer: "Could you clarify your question?" },
  { question: "update", answer: "What would you like to update?" },
  { question: "confirm", answer: "What do you want to confirm?" },
  { question: "recommendation", answer: "What kind of recommendation are you looking for?" },
  { question: "advice", answer: "What advice do you need?" },
  { question: "news", answer: "What news are you interested in?" },
  { question: "feedback", answer: "What feedback do you have for us?" },
  { question: "support", answer: "What support do you need?" },
  { question: "help me out", answer: "Sure! How can I help you out?" },
  { question: "learn", answer: "What would you like to learn today?" },
  { question: "tell me", answer: "Tell me more about what you're looking for." },
  { question: "show me", answer: "What would you like me to show you?" },
  { question: "call", answer: "Would you like to schedule a call?" },
  { question: "email", answer: "What email do you need to contact?" },
  { question: "reply", answer: "What would you like me to reply to?" },
  { question: "yes", answer: "Great! What do you need assistance with?" },
  { question: "no", answer: "Alright, let me know if you need anything later!" },
];



module.exports = predefinedAnswers